### ISSUE TITLE
Hey there, I "cloned" you :)

### ISSUE THREAD

**Issue by ItachiSan** [pm-events/pm-events.github.io#2]
Hi!

I thought it would be useful to mention that I forked and reworked your code; you can see the results here:
https://github.com/ItachiSan/pmex-events

I didn't see any copyright nor license file around here, so I believe there is no issue, but I still wanted to tell you I did what I did. 😄 
Bests,

Giovanni

**Comment by VoltageMiner** [comment]
Closed. This isn't an issue.
